version: '3.9'
services:
    mongo:
        image: mongo
        restart: always
        ports:
          - 27017:27017
        expose:
          - 27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-example}
        networks:
          - database
          - backend

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME:-root}
          ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD:-example}
          ME_CONFIG_MONGODB_URL: ${MONGODB_URL:-mongodb://root:example@mongo:27017/} 
        depends_on:
          - mongo
        networks:
          - database
    
    redis:
        image: redis:6.2.7
        restart: always
        expose:
            - 6379
        networks:
            - backend

    server:
        build: ..
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ..:/home/node/app/
            - /home/node/app/node_modules
        networks:
            - backend
        depends_on:
            - postgres
            - redis
        stdin_open: true
        tty: true

volumes:
    pgdata:
    pgadmin:
networks:
    database:
    backend:
